Default_deck_list_node = { layerElements : [  ], flexWrap : "wrap", gapColumn : 0, gapRow : 0, 
	justifyContent : "center", marginLeft : 0, marginRight : 0, marginTop : 0, marginBottom : 0, 
	nodes : [ { layerElements : [ { textAngle : 0, textColour : -1, textOriginX : 0, type : "Text", 
	textOriginY : 0, textOrigin : 4, textAlignment : 257, textCharacterSpacing : 0, textLineSpacing : 0, 
	textFrameWidth : 352, textFrameHeight : 64, textWrap : 0, textWrapMode : 1, textText : "Test_name", 
	elementId : 75, flexVisible : 1, flexAnchor : "MiddleCentre", flexStretchWidth : 1, 
	flexStretchHeight : 1, flexTileHorizontal : 0, flexTileVertical : 0, flexStretchKeepAspect : 1, 
	elementOrder : 10, textFontIndex : F_menu, textOffsetX : 0, textOffsetY : 0, textScaleX : 1, 
	textScaleY : 1 } ], gapColumn : 0, gapRow : 0, justifyContent : "center", marginLeft : 0, 
	marginRight : 0, marginTop : 0, marginBottom : 0, name : "NameText", clipContent : 0, paddingLeft : 0, 
	paddingRight : 0, paddingTop : 0, width : "95%", paddingBottom : 0, height : "55%", alignItems : "center" }
	,{ layerElements : [ { type : "Sprite", elementId : 76, flexVisible : 1, flexAnchor : "MiddleCentre", 
	flexStretchWidth : 1, flexStretchHeight : 1, flexTileHorizontal : 0, spriteIndex : S_ui_circle, 
	flexTileVertical : 0, spriteOffsetX : 0, flexStretchKeepAspect : 0, spriteOffsetY : 0, 
	elementOrder : 20, spriteScaleX : 1, spriteScaleY : 1, spriteColour : -1, spriteImageSpeed : 1, 
	spriteSpeedType : 0, spriteImageIndex : 0, spriteAngle : 0 } ], gapColumn : 0, gapRow : 0, 
	justifyContent : "center", marginLeft : 0, marginRight : 0, positionType : "absolute", 
	marginTop : 0, marginBottom : 0, name : "UI_sprite", clipContent : 0, paddingLeft : 0, 
	paddingRight : 0, paddingTop : 0, width : "100%", paddingBottom : 0, height : "100%", 
	alignItems : "center" } ], name : "Deck1", clipContent : 0, paddingLeft : 0, paddingRight : 0, 
	paddingTop : 0, width : 175, paddingBottom : 0, height : 175, alignContent : "center" }